### ISSUE TITLE
Create appeal

### ISSUE THREAD

**Issue by aldnav** [ephraimeg/alive-project#2]
Requirement specifications:

- [x] User should be able to create an appeal from a page
- [x] User should be able to set description of the appeal
- [x] User should be able to edit the appeal
- [x] User should be able to cancel an appeal
- [x] User should be able to **see all** appeals

**Comment by boredchinese** [comment]
@ephraimeg Please clarify on the statuses of appeals. In @allenazamoras it's still `INACTIVE`, `ACTIVE`, and `COMPLETED`. I think even you're confused with the naming because when I set something as `INACTIVE`, it shows up in the completed section but when I set something as `COMPLETED`, it doesn't show up anywhere.

Steps: 

1. Create Appeal
2. Go to profile and cancel appeal (it's patched as `COMPLETED`)
3. Refresh page and it won't show up in completed.
4. Manually set it to `INACTIVE` and it'll show up in completed.
